name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Lint
      run: |
        rustup component add clippy
        cargo clippy
    - name: Run tests
      run: cargo test --verbose
